package b_list.utils;

import java.util.Random;

public class DynamicArrayTestBed {
    public static void main(String[] args) {
        DynamicArray myList = new DynamicArray();
        Random rg = new Random();

        for (int i = 0; i < 10; i++) {
            myList.add(rg.nextInt(10)); //adds 10 random nums from 0-9 to dynamicArray
        }

        System.out.println("Index of 5: " + myList.indexOf(5)); //search fro 5
        System.out.println("Index of 20: " + myList.indexOf(20)); //search for 20
        //20 cant be generated by nextInt(10) this should return -1
    }
}
